image: ruby:2.7.4-alpine3.13

services:
  - postgres:13.3

variables:
  RAILS_ENV: test
  SECRET_KEY_BASE: secret_key
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app
  POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
  DATABASE_HOST: postgres
  DATABASE_PORT: 5432
  DATABASE_NAME: app
  DATABASE_USER: app
  DATABASE_PASSWORD: app
  TZ: Asia/Tokyo

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - vendor/bundle

before_script:
  - apk add git g++ make postgresql-dev nodejs yarn tzdata
  - bundle install --jobs $(nproc) --path vendor/bundle
  - yarn install

stages:
  - test

test:
  stage: test
  script:
    - bundle exec rails -v
    - bundle exec rails db:create
    - bundle exec rails db:migrate
    - bundle exec rspec
