services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace
      - bundle_cache:${TREE_VIEW_GEM_BUNDLE_PATH:-/usr/local/bundle}
    tty: true
    stdin_open: true
    environment:
      BUNDLE_PATH: ${TREE_VIEW_GEM_BUNDLE_PATH:-/usr/local/bundle}

volumes:
  bundle_cache:
